package com.fr.adaming.jsfapp.model;

// Generated 13 nov. 2015 10:42:14 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fr.adaming.jsfapp.utils.IConstants;

/**
 * CompteFidelite generated by hbm2java
 */
@Entity
@Table(name = "compte_fidelite", catalog = IConstants.SCHEMA)
public class CompteFidelite implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 3152517390007934221L;
	private long idCmptFedilite;
	private PackCompt packCompt;
	private Marque marque;
	private String NCompt;
	private String nom;
	private String prenom;
	private String portable;
	private String cin;
	private String email;
	private String fonction;
	private String mfEntreprise;
	private String adresseEntreprise;
	private String entreprise1;
	private String entreprise2;
	private String emailEntreprise;
	private String numTelEntreprise;
	private String numFaxEntreprise;

	private String marque_1;
	private String modele;
	private Date datePmc;
	private Boolean FActif;
	private Long nbPoints;
	private String numChassis;
	private CompteFidelite parrain;
	private CompteFidelite chefDePark;
	private Set<CompteFidelite> listChefDePark = new HashSet<CompteFidelite>(0);
	private Set<CompteFidelite> listParrained = new HashSet<CompteFidelite>(0);
	private Set<MouvementFid> mouvementFids = new HashSet<MouvementFid>(0);
	private Set<Sms> smses = new HashSet<Sms>(0);

	public CompteFidelite() {
	}

	public CompteFidelite(long idCmptFedilite) {
		this.idCmptFedilite = idCmptFedilite;
	}

	public CompteFidelite(long idCmptFedilite, PackCompt packCompt, Marque marque, String nCompt, String nom,
			String prenom, String portable, String email, String fonction, String mfEntreprise,
			String adresseEntreprise, String entreprise1, String entreprise2, String emailEntreprise, String marque_1,
			String modele, Date datePmc, Boolean fActif, Long nbPoints, String numChassis, CompteFidelite parrain,
			CompteFidelite chefDePark, Set<CompteFidelite> listChefDePark, Set<CompteFidelite> listParrained,
			Set<MouvementFid> mouvementFids, Set<Sms> smses) {
		super();
		this.idCmptFedilite = idCmptFedilite;
		this.packCompt = packCompt;
		this.marque = marque;
		NCompt = nCompt;
		this.nom = nom;
		this.prenom = prenom;
		this.portable = portable;
		this.email = email;
		this.fonction = fonction;
		this.mfEntreprise = mfEntreprise;
		this.adresseEntreprise = adresseEntreprise;
		this.entreprise1 = entreprise1;
		this.entreprise2 = entreprise2;
		this.emailEntreprise = emailEntreprise;
		this.marque_1 = marque_1;
		this.modele = modele;
		this.datePmc = datePmc;
		FActif = fActif;
		this.nbPoints = nbPoints;
		this.numChassis = numChassis;
		this.parrain = parrain;
		this.chefDePark = chefDePark;
		this.listChefDePark = listChefDePark;
		this.listParrained = listParrained;
		this.mouvementFids = mouvementFids;
		this.smses = smses;
	}

	@Id
	@Column(name = "ID_CMPT_FEDILITE", unique = true, nullable = false, precision = 18, scale = 0)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getIdCmptFedilite() {
		return this.idCmptFedilite;
	}

	public void setIdCmptFedilite(long idCmptFedilite) {
		this.idCmptFedilite = idCmptFedilite;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_PACK_COMPT")
	public PackCompt getPackCompt() {
		return this.packCompt;
	}

	public void setPackCompt(PackCompt packCompt) {
		this.packCompt = packCompt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MARQUE")
	public Marque getMarque() {
		return this.marque;
	}

	public void setMarque(Marque marque) {
		this.marque = marque;
	}

	@Column(name = "N_COMPT", length = 50)
	public String getNCompt() {
		return this.NCompt;
	}

	public void setNCompt(String NCompt) {
		this.NCompt = NCompt;
	}

	@Column(name = "NOM")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "PRENOM")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "PORTABLE", length = 55)
	public String getPortable() {
		return this.portable;
	}

	public void setPortable(String portable) {
		this.portable = portable;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "FONCTION", length = 50)
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	@Column(name = "MF_ENTREPRISE", length = 50)
	public String getMfEntreprise() {
		return this.mfEntreprise;
	}

	public void setMfEntreprise(String mfEntreprise) {
		this.mfEntreprise = mfEntreprise;
	}

	@Column(name = "ADRESSE_ENTREPRISE", length = 50)
	public String getAdresseEntreprise() {
		return this.adresseEntreprise;
	}

	public void setAdresseEntreprise(String adresseEntreprise) {
		this.adresseEntreprise = adresseEntreprise;
	}

	@Column(name = "ENTREPRISE_1", length = 50)
	public String getEntreprise1() {
		return this.entreprise1;
	}

	public void setEntreprise1(String entreprise1) {
		this.entreprise1 = entreprise1;
	}

	@Column(name = "ENTREPRISE_2")
	public String getEntreprise2() {
		return this.entreprise2;
	}

	public void setEntreprise2(String entreprise2) {
		this.entreprise2 = entreprise2;
	}

	@Column(name = "MARQUE", length = 50)
	public String getMarque_1() {
		return this.marque_1;
	}

	public void setMarque_1(String marque_1) {
		this.marque_1 = marque_1;
	}

	@Column(name = "MODELE", length = 50)
	public String getModele() {
		return this.modele;
	}

	public void setModele(String modele) {
		this.modele = modele;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_PMC", length = 10)
	public Date getDatePmc() {
		return this.datePmc;
	}

	public void setDatePmc(Date datePmc) {
		this.datePmc = datePmc;
	}

	@Column(name = "F_ACTIF")
	public Boolean getFActif() {
		return this.FActif;
	}

	public void setFActif(Boolean FActif) {
		this.FActif = FActif;
	}

	@Column(name = "NB_POINTS", precision = 18, scale = 0)
	public Long getNbPoints() {
		return this.nbPoints;
	}

	public void setNbPoints(Long nbPoints) {
		this.nbPoints = nbPoints;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteFidelite")
	public Set<MouvementFid> getMouvementFids() {
		return this.mouvementFids;
	}

	public void setMouvementFids(Set<MouvementFid> mouvementFids) {
		this.mouvementFids = mouvementFids;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "compteFidelite")
	public Set<Sms> getSmses() {
		return this.smses;
	}

	public void setSmses(Set<Sms> smses) {
		this.smses = smses;
	}

	@Column(name = "EMAIL_ENTREPRISE")
	public String getEmailEntreprise() {
		return emailEntreprise;
	}

	public void setEmailEntreprise(String emailEntreprise) {
		this.emailEntreprise = emailEntreprise;
	}

	@Column(name = "NUM_CHASSIS")
	public String getNumChassis() {
		return numChassis;
	}

	public void setNumChassis(String numChassis) {
		this.numChassis = numChassis;
	}

	@ManyToOne
	public CompteFidelite getParrain() {
		return parrain;
	}

	public void setParrain(CompteFidelite parrain) {
		this.parrain = parrain;
	}

	@OneToMany(mappedBy = "parrain")
	public Set<CompteFidelite> getListParrained() {
		return listParrained;
	}

	public void setListParrained(Set<CompteFidelite> listParrained) {
		this.listParrained = listParrained;
	}

	@ManyToOne
	public CompteFidelite getChefDePark() {
		return chefDePark;
	}

	public void setChefDePark(CompteFidelite chefDePark) {
		this.chefDePark = chefDePark;
	}

	@OneToMany(mappedBy = "chefDePark")
	public Set<CompteFidelite> getListChefDePark() {
		return listChefDePark;
	}

	public void setListChefDePark(Set<CompteFidelite> listChefDePark) {
		this.listChefDePark = listChefDePark;
	}

	@Column(name = "TEL_ENTREPRISE")
	public String getNumTelEntreprise() {
		return numTelEntreprise;
	}

	public void setNumTelEntreprise(String numTelEntreprise) {
		this.numTelEntreprise = numTelEntreprise;
	}

	@Column(name = "FAX_ENTREPRISE")
	public String getNumFaxEntreprise() {
		return numFaxEntreprise;
	}

	public void setNumFaxEntreprise(String numFaxEntreprise) {
		this.numFaxEntreprise = numFaxEntreprise;
	}

	@Column(name = "CIN_CHAUFFEUR")
	public String getCin() {
		return cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

}
