package com.fr.adaming.jsfapp.model;

// Generated 13 nov. 2015 10:42:14 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fr.adaming.jsfapp.utils.IConstants;

/**
 * Journal generated by hbm2java
 */
@Entity
@Table(name = "journal", catalog = IConstants.SCHEMA)
public class Journal implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8577698198697180401L;
	private long idLog;
	private Utilisateur utilisateur;
	private String ipprovenance;
	private Date lastConnDate;
	private String navigateurInfo;
	private String actionDesc;
	private String zl1;
	private String zl2;
	private Date timeaction;

	public Journal() {
	}

	public Journal(long idLog, Date timeaction) {
		this.idLog = idLog;
		this.timeaction = timeaction;
	}

	public Journal(long idLog, Utilisateur utilisateur, String ipprovenance, Date lastConnDate, String navigateurInfo,
			String actionDesc, String zl1, String zl2, Date timeaction) {
		this.idLog = idLog;
		this.utilisateur = utilisateur;
		this.ipprovenance = ipprovenance;
		this.lastConnDate = lastConnDate;
		this.navigateurInfo = navigateurInfo;
		this.actionDesc = actionDesc;
		this.zl1 = zl1;
		this.zl2 = zl2;
		this.timeaction = timeaction;
	}

	@Id
	@Column(name = "ID_LOG", unique = true, nullable = false, precision = 18, scale = 0)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getIdLog() {
		return this.idLog;
	}

	public void setIdLog(long idLog) {
		this.idLog = idLog;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_USER")
	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "IPPROVENANCE", length = 50)
	public String getIpprovenance() {
		return this.ipprovenance;
	}

	public void setIpprovenance(String ipprovenance) {
		this.ipprovenance = ipprovenance;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_CONN_DATE", nullable = false, length = 23)
	public Date getLastConnDate() {
		return this.lastConnDate;
	}

	public void setLastConnDate(Date lastConnDate) {
		this.lastConnDate = lastConnDate;
	}

	@Column(name = "NAVIGATEUR_INFO", length = 200)
	public String getNavigateurInfo() {
		return this.navigateurInfo;
	}

	public void setNavigateurInfo(String navigateurInfo) {
		this.navigateurInfo = navigateurInfo;
	}

	@Column(name = "ACTION_DESC", length = 500)
	public String getActionDesc() {
		return this.actionDesc;
	}

	public void setActionDesc(String actionDesc) {
		this.actionDesc = actionDesc;
	}

	@Column(name = "ZL1", length = 500)
	public String getZl1() {
		return this.zl1;
	}

	public void setZl1(String zl1) {
		this.zl1 = zl1;
	}

	@Column(name = "ZL2", length = 500)
	public String getZl2() {
		return this.zl2;
	}

	public void setZl2(String zl2) {
		this.zl2 = zl2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TIMEACTION", nullable = false, length = 23)
	public Date getTimeaction() {
		return this.timeaction;
	}

	public void setTimeaction(Date timeaction) {
		this.timeaction = timeaction;
	}

}
