package com.fr.adaming.jsfapp.model;

// Generated 13 nov. 2015 10:42:14 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fr.adaming.jsfapp.utils.IConstants;

/**
 * Mail generated by hbm2java
 */
@Entity
@Table(name = "MAIL", catalog = IConstants.SCHEMA)
public class Mail implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -658389011543116554L;
	private long idMail;
	private String contenu;
	private long sendBy;
	private String sendTo;
	private Date dateEnvoi;
	private Boolean statut;

	public Mail() {
	}

	public Mail(long idMail, String contenu, long sendBy, String sendTo) {
		this.idMail = idMail;
		this.contenu = contenu;
		this.sendBy = sendBy;
		this.setSendTo(sendTo);
	}

	public Mail(long idMail, String contenu, long sendBy, String sendTo, Date dateEnvoi) {
		this.idMail = idMail;
		this.contenu = contenu;
		this.sendBy = sendBy;
		this.setSendTo(sendTo);
		this.dateEnvoi = dateEnvoi;
	}

	@Id
	@Column(name = "ID_MAIL", unique = true, nullable = false, precision = 18, scale = 0)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getIdMail() {
		return this.idMail;
	}

	public void setIdMail(long idMail) {
		this.idMail = idMail;
	}

	@Column(name = "CONTENU", nullable = false, length = 1000)
	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	@Column(name = "SEND_BY", nullable = false, precision = 18, scale = 0)
	public long getSendBy() {
		return this.sendBy;
	}

	public void setSendBy(long sendBy) {
		this.sendBy = sendBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ENVOI", length = 10)
	public Date getDateEnvoi() {
		return this.dateEnvoi;
	}

	public void setDateEnvoi(Date dateEnvoi) {
		this.dateEnvoi = dateEnvoi;
	}

	@Column(name = "STATUT", columnDefinition = "BIT")
	public Boolean getStatut() {
		return statut;
	}

	public void setStatut(Boolean statut) {
		this.statut = statut;
	}

	@Column(name = "SEND_TO", nullable = false, length = 100)
	public String getSendTo() {
		return sendTo;
	}

	public void setSendTo(String sendTo) {
		this.sendTo = sendTo;
	}

}
