package com.fr.adaming.jsfapp.model;

// Generated 13 nov. 2015 10:42:14 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fr.adaming.jsfapp.utils.IConstants;

/**
 * RefPoint generated by hbm2java
 */
@Entity
@Table(name = "PARAMETRE_MAIL", catalog = IConstants.SCHEMA)
public class ParametreMail implements java.io.Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = -5710993874272853974L;
	private long idParamMail;
	private String host;
	private String login;
	private String motDePasse;
	private Long jobSleep;
	private Boolean factif;

	@Id
	@Column(name = "ID_PARAM_MAIL", unique = true, nullable = false, precision = 18, scale = 0)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getIdParamMail() {
		return idParamMail;
	}

	public void setIdParamMail(long idParamMail) {
		this.idParamMail = idParamMail;
	}

	@Column(name = "HOST_MAIL")
	public String getHost() {
		return host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "LOGIN_MAIL")
	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "MDP_MAIL")
	public String getMotDePasse() {
		return motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	@Column(name = "FACTIF")
	public Boolean getFactif() {
		return factif;
	}

	public void setFactif(Boolean factif) {
		this.factif = factif;
	}

	@Column(name = "JOB_SLEEP", precision = 18, scale = 0)
	public Long getJobSleep() {
		return jobSleep;
	}

	public void setJobSleep(Long jobSleep) {
		this.jobSleep = jobSleep;
	}

}
