package com.fr.adaming.jsfapp.model;

// Generated 13 nov. 2015 10:42:14 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fr.adaming.jsfapp.utils.IConstants;

/**
 * Parametre generated by hbm2java
 */
@Entity
@Table(name = "parametre", catalog = IConstants.SCHEMA)
public class Parametre implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -218041372982824910L;
	private long idParametre;
	private String adresse;
	private String email;
	private String tel;
	private String fax;
	private String nomSociete;
	private Boolean factif;

	public Parametre() {
	}

	public Parametre(long idParametre, String adresse, String email, String tel, String fax, String nomSociete,
			Boolean factif) {
		super();
		this.idParametre = idParametre;
		this.adresse = adresse;
		this.email = email;
		this.tel = tel;
		this.fax = fax;
		this.nomSociete = nomSociete;
		this.factif = factif;
	}

	public Parametre(long idParametre) {
		this.idParametre = idParametre;
	}

	@Id
	@Column(name = "ID_PARAMETRE", unique = true, nullable = false, precision = 18, scale = 0)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getIdParametre() {
		return this.idParametre;
	}

	public void setIdParametre(long idParametre) {
		this.idParametre = idParametre;
	}

	@Column(name = "ADRESSE", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "EMAIL", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TEL", length = 254)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "FAX", length = 254)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "NOM_SOCIETE", length = 254)
	public String getNomSociete() {
		return this.nomSociete;
	}

	public void setNomSociete(String nomSociete) {
		this.nomSociete = nomSociete;
	}

	@Column(name = "FACTIF")
	public Boolean getFactif() {
		return this.factif;
	}

	public void setFactif(Boolean factif) {
		this.factif = factif;
	}

}
