package com.fr.adaming.jsfapp.model;

// Generated 13 nov. 2015 10:42:14 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fr.adaming.jsfapp.utils.IConstants;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "profil", catalog = IConstants.SCHEMA)
public class Profil implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4691610175499148419L;
	private long idProfil;
	private String codProfil;
	private String desProfil;
	private Boolean flagActif;
	private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

	public Profil() {
	}

	public Profil(long idProfil, String codProfil, String desProfil) {
		this.idProfil = idProfil;
		this.codProfil = codProfil;
		this.desProfil = desProfil;
	}

	public Profil(long idProfil, String codProfil, String desProfil, Boolean flagActif, Set<Utilisateur> utilisateurs) {
		this.idProfil = idProfil;
		this.codProfil = codProfil;
		this.desProfil = desProfil;
		this.flagActif = flagActif;
		this.utilisateurs = utilisateurs;
	}

	@Id
	@Column(name = "ID_PROFIL", unique = true, nullable = false, precision = 18, scale = 0)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getIdProfil() {
		return this.idProfil;
	}

	public void setIdProfil(long idProfil) {
		this.idProfil = idProfil;
	}

	@Column(name = "COD_PROFIL", nullable = false, length = 50)
	public String getCodProfil() {
		return this.codProfil;
	}

	public void setCodProfil(String codProfil) {
		this.codProfil = codProfil;
	}

	@Column(name = "DES_PROFIL", nullable = false, length = 250)
	public String getDesProfil() {
		return this.desProfil;
	}

	public void setDesProfil(String desProfil) {
		this.desProfil = desProfil;
	}

	@Column(name = "FLAG_ACTIF")
	public Boolean getFlagActif() {
		return this.flagActif;
	}

	public void setFlagActif(Boolean flagActif) {
		this.flagActif = flagActif;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "profil")
	public Set<Utilisateur> getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
