package com.fr.adaming.jsfapp.model;

// Generated 13 nov. 2015 10:42:14 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.fr.adaming.jsfapp.utils.IConstants;

/**
 * RefPoint generated by hbm2java
 */
@Entity
@Table(name = "PARAMETRE_SMS", catalog = IConstants.SCHEMA)
public class SmsParametre implements java.io.Serializable {
	/**
	 *
	 */
	private static final long serialVersionUID = 3985143258436960423L;
	/**
	 *
	 */
	private long idParamSMS;
	private String login;
	private String passwd;
	private String host;
	private String service;
	private Boolean Factif;

	@Id
	@Column(name = "ID_PARAM_SMS", unique = true, nullable = false, precision = 18, scale = 0)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getIdParamSMS() {
		return idParamSMS;
	}

	public void setIdParamSMS(long idParamSMS) {
		this.idParamSMS = idParamSMS;
	}

	@Column(name = "LOGIN_USER")
	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "PASSWORD_USER")
	public String getPasswd() {
		return passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	@Column(name = "HOST")
	public String getHost() {
		return host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "SERVICE_ENTETE")
	public String getService() {
		return service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Column(name = "F_ACTIF", columnDefinition = "BIT")
	public Boolean getFactif() {
		return Factif;
	}

	public void setFactif(Boolean factif) {
		Factif = factif;
	}

}
