package com.fr.adaming.jsfapp.model;

// Generated 13 nov. 2015 10:42:14 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fr.adaming.jsfapp.utils.IConstants;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", catalog = IConstants.SCHEMA)
public class Utilisateur implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 4015507800701915928L;
	private long idUser;
	private Profil profil;
	private Date dateCreation;
	private Date dateLastLogin;
	private String login;
	private String nom;
	private String cin;
	private String password;
	private String prenom;
	private String tel;
	private String email;
	private String token;
	private Boolean FActif;
	private Set<Journal> journals = new HashSet<>();
	private Set<Automate> automates = new HashSet<>();

	public Utilisateur() {
	}

	public Utilisateur(long idUser) {
		this.idUser = idUser;
	}

	public Utilisateur(long idUser, Profil profil, Date dateCreation, Date dateLastLogin, String login, String nom,
			String cin, String password, String prenom, String tel, String email, String token, Boolean fActif,
			Set<Journal> journals) {
		super();
		this.idUser = idUser;
		this.profil = profil;
		this.dateCreation = dateCreation;
		this.dateLastLogin = dateLastLogin;
		this.login = login;
		this.nom = nom;
		this.cin = cin;
		this.password = password;
		this.prenom = prenom;
		this.tel = tel;
		this.email = email;
		this.token = token;
		FActif = fActif;
		this.journals = journals;
	}

	@Id
	@Column(name = "ID_USER", unique = true, nullable = false, precision = 18, scale = 0)
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public long getIdUser() {
		return this.idUser;
	}

	public void setIdUser(long idUser) {
		this.idUser = idUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ID_PROFIL")
	public Profil getProfil() {
		return this.profil;
	}

	public void setProfil(Profil profil) {
		this.profil = profil;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_CREATION", length = 19)
	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "_DATE_LAST_LOGIN", length = 19)
	public Date getDateLastLogin() {
		return this.dateLastLogin;
	}

	public void setDateLastLogin(Date dateLastLogin) {
		this.dateLastLogin = dateLastLogin;
	}

	@Column(name = "LOGIN", length = 254)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "NOM", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "CIN", length = 8)
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Column(name = "PASSWORD", length = 254)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "PRENOM", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "TEL", length = 254)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "EMAIL", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TOKEN", length = 50)
	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "F_ACTIF")
	public Boolean getFActif() {
		return this.FActif;
	}

	public void setFActif(Boolean FActif) {
		this.FActif = FActif;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "utilisateur")
	public Set<Journal> getJournals() {
		return this.journals;
	}

	public void setJournals(Set<Journal> journals) {
		this.journals = journals;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "utilisateur")
	public Set<Automate> getAutomates() {
		return automates;
	}

	public void setAutomates(Set<Automate> automates) {
		this.automates = automates;
	}

}
